export const allCountryOptions = [
  { value: "US", label: "United States (+1)" },
  { value: "IN", label: "India (+91)" },
  { value: "ID", label: "Indonesia (+62)" },
  { value: "BR", label: "Brazil (+55)" },
  { value: "PK", label: "Pakistan (+92)" },
  { value: "NG", label: "Nigeria (+234)" },
  { value: "BD", label: "Bangladesh (+880)" },
  { value: "RU", label: "Russia (+7)" },
  { value: "MX", label: "Mexico (+52)" },
  { value: "JP", label: "Japan (+81)" },
  { value: "PH", label: "Philippines (+63)" },
  { value: "ET", label: "Ethiopia (+251)" },
  { value: "VN", label: "Vietnam (+84)" },
  { value: "EG", label: "Egypt (+20)" },
  { value: "CD", label: "Democratic Republic of the Congo (+243)" },
  { value: "DE", label: "Germany (+49)" },
  { value: "TR", label: "Turkey (+90)" },
  { value: "TH", label: "Thailand (+66)" },
  { value: "GB", label: "United Kingdom (+44)" },
  { value: "FR", label: "France (+33)" },
  { value: "IT", label: "Italy (+39)" },
  { value: "ZA", label: "South Africa (+27)" },
  { value: "TZ", label: "Tanzania (+255)" },
  { value: "MM", label: "Myanmar (+95)" },
  { value: "KE", label: "Kenya (+254)" },
  { value: "KR", label: "South Korea (+82)" },
  { value: "CO", label: "Colombia (+57)" },
  { value: "ES", label: "Spain (+34)" },
  { value: "UG", label: "Uganda (+256)" },
  { value: "AR", label: "Argentina (+54)" },
  { value: "UA", label: "Ukraine (+380)" },
  { value: "DZ", label: "Algeria (+213)" },
  { value: "PL", label: "Poland (+48)" },
  { value: "SD", label: "Sudan (+249)" },
  { value: "UZ", label: "Uzbekistan (+998)" },
  { value: "MA", label: "Morocco (+212)" },
  { value: "PE", label: "Peru (+51)" },
  { value: "VE", label: "Venezuela (+58)" },
  { value: "NP", label: "Nepal (+977)" },
  { value: "ML", label: "Mali (+223)" },
  { value: "YE", label: "Yemen (+967)" },
  { value: "SG", label: "Singapore" },
  { value: "MY", label: "Malaysia" },
  { value: "TW", label: "Taiwan" },
  { value: "AU", label: "Australia" },
  { value: "NZ", label: "New Zealand" },
  { value: "NL", label: "Netherlands" },
  { value: "SE", label: "Sweden" },
  { value: "NO", label: "Norway" },
  { value: "FI", label: "Finland" },
  { value: "DK", label: "Denmark" },
  { value: "GR", label: "Greece" },
  { value: "CZ", label: "Czech Republic" },
  { value: "HU", label: "Hungary" },
  { value: "RO", label: "Romania" },
  { value: "BG", label: "Bulgaria" },
  { value: "HR", label: "Croatia" },
  { value: "RS", label: "Serbia" },
  { value: "GH", label: "Ghana" },
  { value: "TN", label: "Tunisia" },
  { value: "IQ", label: "Iraq" },
  { value: "IR", label: "Iran" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "QA", label: "Qatar" },
  { value: "OM", label: "Oman" },
  { value: "KW", label: "Kuwait" },
  { value: "ar", label: "Argentina (+54)", code: "54" },
  { value: "au", label: "Australia (+61)", code: "61" },
  { value: "bd", label: "Bangladesh (+880)", code: "880" },
  { value: "be", label: "Belgium (+32)", code: "32" },
  { value: "bj", label: "Benin (+229)", code: "229" },
  { value: "bo", label: "Bolivia (+591)", code: "591" },
  { value: "bw", label: "Botswana (+267)", code: "267" },
  { value: "bg", label: "Bulgaria (+359)", code: "359" },
  { value: "ca", label: "Canada (+1)", code: "1" },
  { value: "cl", label: "Chile (+56)", code: "56" },
  { value: "cn", label: "China (+86)", code: "86" },
  { value: "co", label: "Colombia (+57)", code: "57" },
  { value: "hr", label: "Croatia (+385)", code: "385" },
  { value: "cz", label: "Czech Republic (+420)", code: "420" },
  { value: "dk", label: "Denmark (+45)", code: "45" },
  { value: "ec", label: "Ecuador (+593)", code: "593" },
  { value: "eg", label: "Egypt (+20)", code: "20" },
  { value: "ee", label: "Estonia (+372)", code: "372" },
  { value: "fi", label: "Finland (+358)", code: "358" },
  { value: "fr", label: "France (+33)", code: "33" },
  { value: "ge", label: "Georgia (+995)", code: "995" },
  { value: "de", label: "Germany (+49)", code: "49" },
  { value: "gh", label: "Ghana (+233)", code: "233" },
  { value: "gr", label: "Greece (+30)", code: "30" },
  { value: "gy", label: "Guyana (+592)", code: "592" },
  { value: "hn", label: "Honduras (+504)", code: "504" },
  { value: "hk", label: "Hong Kong (+852)", code: "852" },
  { value: "hu", label: "Hungary (+36)", code: "36" },
  { value: "is", label: "Iceland (+354)", code: "354" },
  { value: "id", label: "Indonesia (+62)", code: "62" },
  { value: "ie", label: "Ireland (+353)", code: "353" },
  { value: "il", label: "Israel (+972)", code: "972" },
  { value: "it", label: "Italy (+39)", code: "39" },
  { value: "jp", label: "Japan (+81)", code: "81" },
  { value: "ke", label: "Kenya (+254)", code: "254" },
  { value: "BA", label: "Bosnia and Herzegovina (+387)" },
  { value: "BW", label: "Botswana (+267)" },
  { value: "BF", label: "Burkina Faso (+226)" },
  { value: "BI", label: "Burundi (+257)" },
  { value: "CV", label: "Cabo Verde (+238)" },
  { value: "KH", label: "Cambodia (+855)" },
  { value: "CM", label: "Cameroon (+237)" },
  { value: "CA", label: "Canada (+1)" },
  { value: "KY", label: "Cayman Islands (+1345)" },
  { value: "CF", label: "Central African Republic (+236)" },
  { value: "TD", label: "Chad (+235)" },
  { value: "CL", label: "Chile (+56)" },
  { value: "CN", label: "China (+86)" },
  { value: "CX", label: "Christmas Island (+61)" },
  { value: "CC", label: "Cocos (Keeling) Islands (+61)" },
  { value: "KM", label: "Comoros (+269)" },
  { value: "CG", label: "Congo, Republic of the (+242)" },
  { value: "CK", label: "Cook Islands (+682)" },
  { value: "CR", label: "Costa Rica (+506)" },
  { value: "CI", label: "Côte d'Ivoire (+225)" },
  { value: "CU", label: "Cuba (+53)" },
  { value: "CW", label: "Curaçao (+599)" },
  { value: "CY", label: "Cyprus (+357)" },
  { value: "DJ", label: "Djibouti (+253)" },
  { value: "DM", label: "Dominica (+1767)" },
  { value: "DO", label: "Dominican Republic (+1809)" },
  { value: "EC", label: "Ecuador (+593)" },
  { value: "SV", label: "El Salvador (+503)" },
  { value: "GQ", label: "Equatorial Guinea (+240)" },
  { value: "ER", label: "Eritrea (+291)" },
  { value: "EE", label: "Estonia (+372)" },
  { value: "FK", label: "Falkland Islands (+500)" },
  { value: "FO", label: "Faroe Islands (+298)" },
  { value: "FJ", label: "Fiji (+679)" },
];
